import type { SourceKind, SourcePriority, SourceTrustLevel } from '@/types';

export interface SourceConfig {
  id: string;
  name: string;
  kind: SourceKind;
  url: string;
  enabled: boolean;
  priority: SourcePriority;
  trustLevel: SourceTrustLevel;
  tags: string[];
  notes?: string;
}

/** Initial sources — enable 6-8 low-risk, high-quality sources first */
export const SOURCES: SourceConfig[] = [
  // ── Phase 4: RSS / Deal Discovery ────────────────────────────────────
  {
    id: 'hackernews-rss',
    name: 'Hacker News',
    kind: 'rss',
    url: 'https://news.ycombinator.com/rss',
    enabled: true,
    priority: 'medium',
    trustLevel: 'medium',
    tags: ['dev', 'ai', 'saas', 'launch'],
    notes: 'Good for dev tools and AI launches, needs strong scoring to filter noise',
  },
  {
    id: 'producthunt-rss',
    name: 'Product Hunt',
    kind: 'rss',
    url: 'https://www.producthunt.com/feed',
    enabled: true,
    priority: 'high',
    trustLevel: 'high',
    tags: ['ai', 'saas', 'launch'],
    notes: 'Best for AI/SaaS launches with deal offers',
  },
  {
    id: 'betalist-rss',
    name: 'BetaList',
    kind: 'rss',
    url: 'https://betalist.com/feed',
    enabled: true,
    priority: 'medium',
    trustLevel: 'medium',
    tags: ['startup', 'early-access', 'saas'],
    notes: 'Early-access deals, variable quality',
  },
  {
    id: 'dev-to-rss',
    name: 'DEV.to — free tools tag',
    kind: 'rss',
    url: 'https://dev.to/feed/tag/freetools',
    enabled: false,
    priority: 'low',
    trustLevel: 'medium',
    tags: ['dev', 'tools', 'freetools'],
    notes: 'Dev community posts about free tools',
  },
  // ── Phase 4: Official Vendor Blogs (RSS) ─────────────────────────────
  {
    id: 'github-blog-rss',
    name: 'GitHub Blog',
    kind: 'rss',
    url: 'https://github.blog/feed/',
    enabled: true,
    priority: 'high',
    trustLevel: 'high',
    tags: ['dev', 'credits', 'official'],
    notes: 'GitHub Education, Copilot updates, free tiers',
  },
  {
    id: 'github-education-blog',
    name: 'GitHub Education Blog',
    kind: 'rss',
    url: 'https://github.blog/tag/education/feed/',
    enabled: true,
    priority: 'high',
    trustLevel: 'high',
    tags: ['education', 'devtools', 'credits', 'official'],
    notes: 'GitHub Student Developer Pack updates, free credits for students',
  },
  {
    id: 'jetbrains-blog-rss',
    name: 'JetBrains Blog',
    kind: 'rss',
    url: 'https://blog.jetbrains.com/feed/',
    enabled: true,
    priority: 'medium',
    trustLevel: 'high',
    tags: ['devtools', 'education', 'official'],
    notes: 'JetBrains free licenses, student programs, new free-tier tools',
  },
  {
    id: 'aws-blog-rss',
    name: 'AWS News Blog',
    kind: 'rss',
    url: 'https://aws.amazon.com/blogs/aws/feed/',
    enabled: false,
    priority: 'medium',
    trustLevel: 'high',
    tags: ['cloud', 'credits', 'official'],
    notes: 'AWS free tier announcements, credit programs',
  },
  {
    id: 'vercel-blog-rss',
    name: 'Vercel Blog',
    kind: 'rss',
    url: 'https://vercel.com/blog/rss.xml',
    enabled: false,
    priority: 'medium',
    trustLevel: 'high',
    tags: ['devtools', 'cloud', 'official'],
    notes: 'Vercel free tier updates, Next.js announcements',
  },
  {
    id: 'supabase-blog-rss',
    name: 'Supabase Blog',
    kind: 'rss',
    url: 'https://supabase.com/blog/rss.xml',
    enabled: false,
    priority: 'medium',
    trustLevel: 'high',
    tags: ['cloud', 'devtools', 'official'],
    notes: 'Supabase free tier, credits, new features',
  },
  // ── Phase 4: Curated AI Tool Directories ─────────────────────────────
  {
    id: 'theresanaiforthat-rss',
    name: "There's An AI For That",
    kind: 'rss',
    url: 'https://theresanaiforthat.com/rss/',
    enabled: false,
    priority: 'high',
    trustLevel: 'medium',
    tags: ['ai', 'curated', 'tools'],
    notes: 'Curated AI tool directory — filter for free/freemium entries',
  },
  {
    id: 'futuretools-html',
    name: 'FutureTools',
    kind: 'html',
    url: 'https://www.futuretools.io/',
    enabled: false,
    priority: 'high',
    trustLevel: 'medium',
    tags: ['ai', 'curated', 'tools'],
    notes: 'AI tools directory with free tier filter — needs HTML collector',
  },
  {
    id: 'saashub-html',
    name: 'SaaSHub — Free Alternatives',
    kind: 'html',
    url: 'https://www.saashub.com/free',
    enabled: false,
    priority: 'medium',
    trustLevel: 'medium',
    tags: ['saas', 'curated', 'alternatives'],
    notes: 'Free SaaS alternatives directory — needs HTML collector',
  },
  // ── Phase 4: Official Vendor Pages (HTML) ────────────────────────────
  {
    id: 'epicgames-free-html',
    name: 'Epic Games Free Games',
    kind: 'html',
    url: 'https://store.epicgames.com/en-US/free-games',
    enabled: false,
    priority: 'medium',
    trustLevel: 'high',
    tags: ['gaming', 'official'],
    notes: 'Epic weekly free games — no RSS available, requires HTML collector',
  },
  // ── Phase 4: Ecommerce / Voucher VN ──────────────────────────────────
  {
    id: 'mmo4me-rss',
    name: 'MMO4ME — Deals & Vouchers',
    kind: 'rss',
    url: 'https://mmo4me.com/forums/-/index.rss',
    enabled: false,
    priority: 'medium',
    trustLevel: 'medium',
    tags: ['voucher', 'ecommerce', 'vn'],
    notes: 'Vietnamese deal community — variable quality, enable cautiously',
  },
  // ── Phase 7+: Community Sources (disabled until scoring is solid) ─────
  {
    id: 'reddit-saas',
    name: 'Reddit — r/SaaS',
    kind: 'reddit',
    url: 'https://www.reddit.com/r/SaaS/.rss',
    enabled: false,
    priority: 'medium',
    trustLevel: 'medium',
    tags: ['community', 'saas', 'launch'],
    notes: 'Phase 7+: founder promos and launch deals — high noise',
  },
  {
    id: 'reddit-sideproject',
    name: 'Reddit — r/SideProject',
    kind: 'reddit',
    url: 'https://www.reddit.com/r/SideProject/.rss',
    enabled: false,
    priority: 'low',
    trustLevel: 'medium',
    tags: ['community', 'launch', 'saas'],
    notes: 'Phase 7+: indie launches with promo codes — filter for freebie keywords',
  },
  {
    id: 'reddit-entrepreneur',
    name: 'Reddit — r/Entrepreneur',
    kind: 'reddit',
    url: 'https://www.reddit.com/r/Entrepreneur/.rss',
    enabled: false,
    priority: 'low',
    trustLevel: 'medium',
    tags: ['community', 'saas', 'deals'],
    notes: 'Phase 7+: occasional deal posts from founders',
  },
  {
    id: 'twitter-ai-hunters',
    name: 'X/Twitter — AI Tool Hunters List',
    kind: 'twitter',
    url: 'https://twitter.com/i/lists/placeholder',
    enabled: false,
    priority: 'medium',
    trustLevel: 'low',
    tags: ['social', 'ai', 'launch'],
    notes: 'Phase 7+: early deal signals from AI founders — URL TBD, requires Twitter API v2',
  },
];
